name: polypass
description: A password manager written in Dart/Flutter

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-0"

dependencies:
  bloc: ^8.0.3
  equatable: ^2.0.3
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.3
  go_router: ^3.0.7
  json_annotation: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
